// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"database/sql"
	"task-management-be/src/modules/user/handler"
	"task-management-be/src/modules/user/service"
)

// Injectors from wire.go:

func ProvideUserInjection(db *sql.DB) *handler.UserController {
	userService := services.NewUserService()
	userController := handler.NewUserController(userService)
	return userController
}
